// Generated by https://quicktype.io

class FavoriteDAO {
  
  int id;
  String overview;
  String posterPath;
  String title;
  double voteAverage;
  String backdropPath;
  String email;

  FavoriteDAO({
    this.backdropPath,
    this.id,
    this.overview,
    this.posterPath,
    this.title,
    this.voteAverage,
    this.email,
  });

  factory FavoriteDAO.fromJSON(Map<String,dynamic> map){
    return FavoriteDAO(
      backdropPath: map['backdrop_path'],
      id          : map['id'],
      overview:         map['overview'],
      posterPath:       map['poster_path'],
      title:            map['title'],
      voteAverage:      map['vote_average'] is int ? (map['vote_average'] as int).toDouble() : map['vote_average'],
      email:        map['email']
    );
  }

   Map<String, dynamic> toJSON(){
    return{
      "id": id,
      "backdrop_path": backdropPath,
      "overview": overview,
      "poster_path": posterPath,
      "title": title,
      "vote_average": voteAverage,
      "email": email
       
    };
  }
 
}
