// Generated by https://quicktype.io

class ImagesDAO {
 
  String file_path;
  int height;
  int width;

  ImagesDAO({
    this.file_path,
    this.height,
    this.width,
  });
  factory ImagesDAO.fromJSON(Map<String,dynamic> map ){
    return ImagesDAO(
      file_path: map['file_path'],
      height: map['height'],
      width: map['width'],
    );
  }
}
