// Generated by https://quicktype.io

class TrailerDAO {
  String id;
  String key;
  String name;
  String site;
  int size;
  String type;

  TrailerDAO({
    this.id,
    this.key,
    this.name,
    this.site,
    this.size,
    this.type,
  });

  factory TrailerDAO.fromJSON(Map<String,dynamic> map){
    return TrailerDAO(
      id          : map['id'],
      key: map['key'],
      name:    map['name'],
      size:         map['size'],
      site:       map['site'],
      type:       map['type'],
      
    );
  }
}
